name: Compilar Mod Minecraft

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo fonte
        uses: actions/checkout@v4

      - name: Configurar Java JDK (Java 21)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Dar permissao de execucao ao Gradle
        run: chmod +x gradlew

      - name: Compilar o Mod
        run: ./gradlew build

      - name: Salvar arquivo .jar (Artefato)
        uses: actions/upload-artifact@v4
        with:
          name: Arquivo-Mod-Jar
          path: build/libs/*.jar
